### ISSUE TITLE
why the yolov3.cfg not change into gaussian_yolo.cfg

### ISSUE THREAD

**Issue by wgh-2018** [xuannianz/keras-GaussianYOLOv3#19]
i want to know if why the yolov3.cfg not change into gaussian_yolo.cfg? if the network dont need change? 
thank you

**Comment by xuannianz** [comment]
Hi @wgh-2018, yolov3.cfg is used to convert trained yolo weights instead of building network.

**Comment by wgh-2018** [comment]
I want to ask another question..
i tested the model by the inference.py,get the error as fellows
Traceback (most recent call last):
  File "inference.py", line 14, in <module>
    model.load_weights('checkpoints/2020-02-11/pascal_50_4.5823_4.2341.h5', by_name=True)
  File "/home/yp/.local/lib/python3.5/site-packages/keras/engine/saving.py", line 458, in load_wrapper
    return load_function(*args, **kwargs)
  File "/home/yp/.local/lib/python3.5/site-packages/keras/engine/network.py", line 1214, in load_weights
    reshape=reshape)
  File "/home/yp/.local/lib/python3.5/site-packages/keras/engine/saving.py", line 1290, in load_weights_from_hdf5_group_by_name
    str(weight_values[i].shape) + '.')
ValueError: Layer #249 (named "conv2d_59"), weight <tf.Variable 'conv2d_59/kernel:0' shape=(1, 1, 1024, 87) dtype=float32_ref> has shape (1, 1, 1024, 87), but the saved weight has shape (30, 1024, 1, 1)
